# Generated by Django 4.2.21 on 2025-05-28 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_opportunity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunity',
            name='date_created',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='updated_on',
            field=models.CharField(blank=True, null=True),
        ),
    ]
