# Generated by Django 4.2.21 on 2025-05-28 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_opportunity_date_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='booked_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
