# Generated by Django 4.2.21 on 2025-05-28 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_ghlauthcredentials_location_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='location_id',
            field=models.CharField(blank=True, default='YKNrPJlQoiFjFbjxjGMC', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='location_name',
            field=models.CharField(blank=True, default='Alpha Dental Excellence Dr. Arpan Patel', max_length=255, null=True),
        ),
    ]
