# Generated by Django 4.2.21 on 2025-05-28 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_opportunity_location_id_opportunity_location_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunity',
            name='location_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='location_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
