# Generated by Django 4.2.21 on 2025-05-29 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_webhooklog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opportunity',
            name='notes',
        ),
    ]
