# Generated by Django 4.2.21 on 2025-05-29 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_customfield'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='notes',
            field=models.TextField(default='No Data'),
        ),
    ]
