# Generated by Django 4.2.21 on 2025-05-29 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_opportunity_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ghlauthcredentials',
            name='user_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
